services:
  ktrends:
    build: .
    container_name: ktrends
    image: falconchen/ktrends:${PLATFORM:-arm64}-latest
    volumes:
      - ./:/app
    environment:
      - TZ=${TZ:-Asia/Shanghai}
    ports:
      - "${APP_PORT:-8000}:8000"
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
